#!/usr/bin/env node

import { WorldGenerator } from './generators/world.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Parse command line arguments
const args = process.argv.slice(2);
const seedArg = args.find(arg => arg.startsWith('--seed='));
const seed = seedArg ? parseInt(seedArg.split('=')[1]) : Date.now();

console.log('\n═══════════════════════════════════════════════════════');
console.log('         🌌 GENESIS - World Generator 🌌');
console.log('═══════════════════════════════════════════════════════\n');

// Generate the world
const generator = new WorldGenerator(seed);
const world = generator.generate();

// Create output directory
const outputDir = path.join(__dirname, '../generated');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Save JSON data
console.log('\n💾 Saving world data...');
const jsonPath = path.join(outputDir, `world_${seed}.json`);
fs.writeFileSync(jsonPath, JSON.stringify(world, null, 2));
console.log(`   ✓ JSON saved: ${jsonPath}`);

// Generate markdown documentation
console.log('\n📝 Generating documentation...');
generateMarkdownDocs(world, outputDir, seed);

console.log('\n═══════════════════════════════════════════════════════');
console.log('                  🎉 COMPLETE! 🎉');
console.log('═══════════════════════════════════════════════════════');
console.log(`\n📂 Output directory: ${outputDir}`);
console.log(`🌍 World seed: ${seed}`);
console.log(`\nTo regenerate this world: npm run generate -- --seed=${seed}\n`);

function generateMarkdownDocs(world, outputDir, seed) {
  const docsDir = path.join(outputDir, `world_${seed}_docs`);
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
  }

  // Index
  generateIndexDoc(world, docsDir);

  // Geography
  generateGeographyDoc(world.geography, docsDir);

  // Cultures
  world.cultures.forEach(culture => {
    generateCultureDoc(culture, docsDir);
  });

  // History
  generateHistoryDoc(world.history, docsDir);

  // Mythology
  generateMythologyDoc(world.mythology, docsDir);

  console.log(`   ✓ Documentation generated in: ${docsDir}`);
}

function generateIndexDoc(world, docsDir) {
  const md = `# ${world.name}

*A procedurally generated world*

**Generated:** ${new Date(world.metadata.generatedAt).toLocaleString()}
**Seed:** ${world.metadata.seed}

## World Overview

${world.name} is a rich and diverse world with ${world.statistics.geography.continentCount} continents,
${world.statistics.cultures.total} distinct cultures, and a deep history spanning ${world.statistics.history.currentYear} years.

### Geography

- **Continents:** ${world.geography.continents.map(c => c.name).join(', ')}
- **Oceans:** ${world.geography.oceans.map(o => o.name).join(', ')}
- **Climate:** ${world.geography.climate.globalTemperature}
- **Natural Wonders:** ${world.statistics.geography.naturalWonders}

### Cultures

${world.cultures.map((c, i) => `${i + 1}. **${c.name}** - ${c.location.continent}, ${c.government.type} government`).join('\n')}

### Current Age

**${world.history.currentAge.name}** (Year ${world.history.timeline.currentYear})

${world.history.currentAge.characteristics.map(c => `- ${c}`).join('\n')}

## Documentation

- [Geography](./geography.md) - Detailed geographic information
- [History](./history.md) - Complete historical timeline
- [Mythology](./mythology.md) - Myths, legends, and beliefs

### Cultures

${world.cultures.map(c => `- [${c.name}](./culture_${c.id}.md)`).join('\n')}

---

*Generated by Genesis World Generator v${world.metadata.version}*
`;

  fs.writeFileSync(path.join(docsDir, 'index.md'), md);
}

function generateGeographyDoc(geography, docsDir) {
  let md = `# Geography of ${geography.name}

## Global Climate

**Temperature:** ${geography.climate.globalTemperature}

**Weather Patterns:**
${geography.climate.weatherPatterns.map(p => `- ${p}`).join('\n')}

${geography.climate.magicalInfluence.present ? `
**Magical Influences:**
${geography.climate.magicalInfluence.effects.map(e => `- ${e}`).join('\n')}
` : ''}

## Continents

`;

  geography.continents.forEach(continent => {
    md += `
### ${continent.name}

**Size:** ${continent.size}

#### Terrain

${continent.terrain.map(t => `- **${t.type}** (${t.coverage}): ${t.description}`).join('\n')}

#### Climate

**Zones:** ${continent.climate.zones.join(', ')}
**Rainfall:** ${continent.climate.rainfall}
**Temperature:** ${continent.climate.temperature}

**Seasons:**
${continent.climate.seasons.map(s => `- **${s.name}** (${s.duration}): ${s.characteristics.join(', ')}`).join('\n')}

#### Regions

${continent.regions.map(r => `- **${r.name}** (${r.type})\n  - ${r.features.join(', ')}`).join('\n')}

---
`;
  });

  md += `
## Oceans

${geography.oceans.map(o => `
### ${o.name}

**Depth:** ${o.depth}

**Characteristics:**
${o.characteristics.map(c => `- ${c}`).join('\n')}
`).join('\n')}

## Natural Wonders

${geography.naturalWonders.map(w => `
### ${w.name}

**Location:** ${w.location.region}, ${w.location.continent}
**Type:** ${w.type}
**Significance:** ${w.significance}

${w.description}
`).join('\n')}

## Resources

${geography.resources.map(r => `
- **${r.type}** in ${r.location.regions.join(', ')} (${r.location.continent})
  - Abundance: ${r.abundance}
  - Importance: ${r.importance}
`).join('\n')}
`;

  fs.writeFileSync(path.join(docsDir, 'geography.md'), md);
}

function generateCultureDoc(culture, docsDir) {
  const md = `# ${culture.name}

## Overview

**Location:** ${culture.location.region}, ${culture.location.continent}
**Terrain:** ${culture.location.terrain}
**Climate:** ${culture.location.climate}

## Demographics

**Population Size:** ${culture.population.size}
**Distribution:** ${culture.population.distribution}
**Growth:** ${culture.population.growth}
**Diversity:** ${culture.population.diversity}

## Government

**Type:** ${culture.government.type}
**Stability:** ${culture.government.stability}
**Corruption:** ${culture.government.corruption}
**Succession:** ${culture.government.succession}

**Power Structure:**
- Central Control: ${culture.government.powerStructure.centralizedControl}
- Regional Autonomy: ${culture.government.powerStructure.regionalAutonomy}
- Key Factions: ${culture.government.powerStructure.keyFactions.join(', ')}

## Values & Beliefs

**Core Values:**
${culture.values.core.map(v => `- ${v}`).join('\n')}

**Virtues:**
${culture.values.virtues.map(v => `- ${v}`).join('\n')}

**Taboos:**
${culture.values.taboos.map(t => `- ${t}`).join('\n')}

## Customs & Traditions

**Greetings:** ${culture.customs.greetings}

### Coming of Age

**Age:** ${culture.customs.comingOfAge.age}
**Ceremony:** ${culture.customs.comingOfAge.ceremony}
**Significance:** ${culture.customs.comingOfAge.significance}

### Marriage

**Arrangement:** ${culture.customs.marriage.arrangement}
**Ceremony:** ${culture.customs.marriage.ceremony}
**Structure:** ${culture.customs.marriage.structure}
${culture.customs.marriage.dowry !== 'no dowry tradition' ? `**Dowry:** ${culture.customs.marriage.dowry}` : ''}

### Death Rituals

**Body Treatment:** ${culture.customs.death.bodyTreatment}
**Mourning:** ${culture.customs.death.mourning}
**Afterlife Belief:** ${culture.customs.death.afterlife}

### Festivals

${culture.customs.festivals.map(f => `
#### ${f.name}

**Timing:** ${f.timing}
**Purpose:** ${f.purpose}
**Activities:** ${f.activities.join(', ')}
`).join('\n')}

### Daily Rituals

${culture.customs.dailyRituals.map(r => `- ${r}`).join('\n')}

## Arts & Culture

**Visual Arts:** ${culture.arts.visualArts.join(', ')}
**Performing Arts:** ${culture.arts.performingArts.join(', ')}
**Literary Arts:** ${culture.arts.literaryArts.join(', ')}
**Significance:** ${culture.arts.significance}

## Technology

**Era:** ${culture.technology.era}
**Metalworking:** ${culture.technology.metalworking}
**Agriculture:** ${culture.technology.agriculture}
**Construction:** ${culture.technology.construction}
**Seafaring:** ${culture.technology.seafaring}
**Warfare:** ${culture.technology.warfare}

**Specializations:**
${culture.technology.specializations.map(s => `- ${s}`).join('\n')}

## Religion

**Type:** ${culture.religion.type}
**Temples:** ${culture.religion.temples}
**Influence:** ${culture.religion.influence}

**Practices:**
${culture.religion.practices.map(p => `- ${p}`).join('\n')}

### Clergy

**Structure:** ${culture.religion.clergy.structure}
**Power:** ${culture.religion.clergy.power}
**Requirements:** ${culture.religion.clergy.requirements.join(', ')}

${culture.religion.pantheon ? `
### Pantheon

${culture.religion.pantheon.map(g => `
- **${g.domain}**: ${g.characteristics}, ${g.worship}
`).join('\n')}
` : ''}

## Economy

**Basis:** ${culture.economy.basis}
**Currency:** ${culture.economy.currency}
**Wealth Distribution:** ${culture.economy.wealthDistribution}

**Trade:**
- Extent: ${culture.economy.trade.extent}
- Attitude: ${culture.economy.trade.attitude}

**Resources:**
${culture.economy.resources.map(r => `- ${r}`).join('\n')}

## Military

**Structure:** ${culture.military.structure}
**Strength:** ${culture.military.strength}
**Philosophy:** ${culture.military.philosophy}

**Specializations:**
${culture.military.specialization.map(s => `- ${s}`).join('\n')}

## Architecture

**Materials:** ${culture.architecture.materials.join(', ')}
**Style:** ${culture.architecture.style}
**Urban Planning:** ${culture.architecture.urbanPlanning}

**Notable Features:**
${culture.architecture.notableFeatures.map(f => `- ${f}`).join('\n')}

## Cuisine

**Staples:** ${culture.cuisine.staples.join(', ')}
**Flavors:** ${culture.cuisine.flavors.join(', ')}
**Preparation:** ${culture.cuisine.preparation.join(', ')}
**Significance:** ${culture.cuisine.significance}

## Social Structure

**Social Mobility:** ${culture.socialStructure.mobility}
**Family Structure:** ${culture.socialStructure.family}
**Age Hierarchy:** ${culture.socialStructure.ageHierarchy}

### Social Classes

${culture.socialStructure.classes.map(c => `
- **${c.name}**
  - Privileges: ${c.privileges}
  - Restrictions: ${c.restrictions}
`).join('\n')}

### Gender Roles

**Type:** ${culture.socialStructure.gender.type}
**Leadership:** ${culture.socialStructure.gender.leadership}
**Restrictions:** ${culture.socialStructure.gender.restrictions}

## Language

**Name:** ${culture.language.name}
**Family:** ${culture.language.family.family}
**Status:** ${culture.language.status}

See [Language Reference](./language_${culture.language.id}.md) for detailed linguistic information.
`;

  fs.writeFileSync(path.join(docsDir, `culture_${culture.id}.md`), md);

  // Also generate language doc
  generateLanguageDoc(culture.language, docsDir);
}

function generateLanguageDoc(language, docsDir) {
  const md = `# ${language.name}

*Language of the ${language.cultureName}*

## Overview

**Family:** ${language.family.family}
**Speakers:** ${language.speakers}
**Status:** ${language.status}

**Influences:**
${language.family.influences.map(i => `- ${i}`).join('\n')}

## Phonology

**Consonants:** ${language.phonology.consonants}
**Vowels:** ${language.phonology.vowels}
**Syllable Structure:** ${language.phonology.syllableStructure}
**Stress:** ${language.phonology.stress}

${language.phonology.tone.present ? `
**Tone System:** ${language.phonology.tone.type}
` : ''}

${language.phonology.distinctiveFeatures.length > 0 ? `
**Distinctive Features:**
${language.phonology.distinctiveFeatures.map(f => `- ${f}`).join('\n')}
` : ''}

## Grammar

**Word Order:** ${language.grammar.wordOrder}
**Alignment:** ${language.grammar.alignment}
**Complexity:** ${language.grammar.complexity}

### Case System

**Count:** ${language.grammar.case.count}
${language.grammar.case.cases.length > 0 ? `**Cases:** ${language.grammar.case.cases.join(', ')}` : ''}
**Marking:** ${language.grammar.case.marking}

### Verb System

**Tenses:** ${language.grammar.verbSystem.tenses.join(', ')}
**Aspects:** ${language.grammar.verbSystem.aspects.join(', ')}
**Moods:** ${language.grammar.verbSystem.moods.join(', ')}
**Voice:** ${language.grammar.verbSystem.voice.join(', ')}
**Agreement:** ${language.grammar.verbSystem.agreement}

### Noun System

**Gender:** ${language.grammar.nounSystem.gender}
**Number:** ${language.grammar.nounSystem.number}
**Definiteness:** ${language.grammar.nounSystem.definiteness}
**Possession:** ${language.grammar.nounSystem.possession}

## Writing System

${language.writing.type === 'oral tradition only' ? `
This language has no writing system and exists solely in oral tradition.
` : `
**Type:** ${language.writing.type}
**Direction:** ${language.writing.direction}
**Characters:** ${language.writing.characters}
**Materials:** ${language.writing.materials.join(', ')}
**Literacy:** ${language.writing.literacy}
**Age:** ${language.writing.age}
`}

## Vocabulary

### Basic Words

${language.vocabulary.examples.map(w => `- ${w.concept}: *${w.phoneme}*`).join('\n')}

### Loanwords

${language.vocabulary.loanwords.map(l => `- ${l}`).join('\n')}

### Specialized Vocabulary

${language.vocabulary.specializedVocabulary.map(s => `- ${s}`).join('\n')}

## Dialects

${language.dialects.map(d => `
### ${d.name}

**Region:** ${d.region}
**Distinctiveness:** ${d.distinctiveness}
**Features:** ${d.features.join(', ')}
`).join('\n')}

## Literary Tradition

${language.literaryTradition.exists ? `
**Age:** ${language.literaryTradition.age}
**Canonical Works:** ${language.literaryTradition.canonicalWorks}

**Forms:**
${language.literaryTradition.forms.map(f => `- ${f}`).join('\n')}
` : `
This language has minimal or no literary tradition.
`}
`;

  fs.writeFileSync(path.join(docsDir, `language_${language.id}.md`), md);
}

function generateHistoryDoc(history, docsDir) {
  const md = `# Historical Timeline

**Current Year:** ${history.timeline.currentYear}
**Calendar System:** ${history.timeline.calendar.daysInYear} days per year, ${history.timeline.calendar.monthCount} months
**Epoch Start:** ${history.timeline.epochStart}

## Eras

${history.eras.map(era => `
### ${era.name}

**Duration:** ${era.startYear} - ${era.endYear} (${era.duration})
**Dominant Cultures:** ${era.dominantCultures.join(', ')}

**Characteristics:**
${era.characteristics.map(c => `- ${c}`).join('\n')}

**Key Developments:**
${era.keyDevelopments.map(d => `- ${d}`).join('\n')}
`).join('\n')}

## Current Age

**${history.currentAge.name}** (Year ${history.currentAge.yearInEra} of this era)

${history.currentAge.characteristics.map(c => `- ${c}`).join('\n')}

## Major Events

${history.majorEvents.map(event => `
### Year ${event.year}: ${event.name}

**Era:** ${event.era}
**Type:** ${event.type}
**Impact:** ${event.impact}

${event.description}

**Participants:** ${event.participants.join(', ')}

**Consequences:**
${event.consequences.map(c => `- ${c}`).join('\n')}
`).join('\n')}

## Conflicts

${history.conflicts.map(conflict => `
### ${conflict.name}

**Duration:** ${conflict.duration}
**Participants:** ${conflict.participants.join(', ')}
**Cause:** ${conflict.cause}
**Casualties:** ${conflict.casualties}

**Outcome:**
- Type: ${conflict.outcome.type}
${conflict.outcome.victor ? `- Victor: ${conflict.outcome.victor}` : ''}
- Territorial Changes: ${conflict.outcome.territories}
${conflict.outcome.reparations ? '- Reparations paid' : ''}

**Legacy:**
${conflict.legacy.map(l => `- ${l}`).join('\n')}
`).join('\n')}

## Alliances

${history.alliances.map(alliance => `
### ${alliance.name}

**Members:** ${alliance.members.join(', ')}
**Formed:** ${alliance.formed}
**Status:** ${alliance.status}
**Strength:** ${alliance.strength}

**Purpose:** ${alliance.purpose}

**Achievements:**
${alliance.achievements.map(a => `- ${a}`).join('\n')}
`).join('\n')}

## Major Discoveries

${history.discoveries.map(discovery => `
### ${discovery.name}

**Year:** ${discovery.year}
**Discovered by:** ${discovery.discoveredBy}
**Type:** ${discovery.type}
**Impact:** ${discovery.impact}
**Current Status:** ${discovery.currentStatus}
`).join('\n')}
`;

  fs.writeFileSync(path.join(docsDir, 'history.md'), md);
}

function generateMythologyDoc(mythology, docsDir) {
  let md = `# Mythology and Beliefs

## Cosmology

**Structure:** ${mythology.cosmology.structure}

### Cosmic Realms

**Count:** ${mythology.cosmology.realms.count}
**Connections:** ${mythology.cosmology.realms.connections}

**Realms:**
${mythology.cosmology.realms.realms.map(r => `- ${r}`).join('\n')}

### Celestial Bodies

**Sun:** ${mythology.cosmology.celestialBodies.sun.nature}
**Moon:** ${mythology.cosmology.celestialBodies.moon.nature} (Phases represent: ${mythology.cosmology.celestialBodies.moon.phases})
**Stars:** ${mythology.cosmology.celestialBodies.stars}
**Constellations:** ${mythology.cosmology.celestialBodies.constellations}

### Afterlife

${mythology.cosmology.afterlife.type === 'single destination' ? `
**Type:** Single destination
**Realm:** ${mythology.cosmology.afterlife.realm}
` : `
**Type:** Multiple destinations
**Criteria:** ${mythology.cosmology.afterlife.criteria}

**Destinations:**
${mythology.cosmology.afterlife.destinations.map(d => `- ${d}`).join('\n')}
`}

## Shared Myths

${mythology.sharedMyths.deluge ? `
### The Great Deluge

**Cause:** ${mythology.sharedMyths.deluge.cause}
**Survivors:** ${mythology.sharedMyths.deluge.survivors}
**Aftermath:** ${mythology.sharedMyths.deluge.aftermath}

${mythology.sharedMyths.deluge.variations}
` : ''}

${mythology.sharedMyths.goldenAge ? `
### The Golden Age

${mythology.sharedMyths.goldenAge.period}

**Characteristics:**
${mythology.sharedMyths.goldenAge.characteristics.map(c => `- ${c}`).join('\n')}

**Ending:** ${mythology.sharedMyths.goldenAge.ending}
${mythology.sharedMyths.goldenAge.hope}
` : ''}

${mythology.sharedMyths.apocalypse ? `
### ${mythology.sharedMyths.apocalypse.name}

**Outcome:** ${mythology.sharedMyths.apocalypse.outcome}

**Triggers:**
${mythology.sharedMyths.apocalypse.triggers.map(t => `- ${t}`).join('\n')}

**Signs:**
${mythology.sharedMyths.apocalypse.signs.map(s => `- ${s}`).join('\n')}
` : ''}

## Cultural Mythologies

${mythology.culturalMythologies.map(cultMyth => `
---

## ${cultMyth.cultureName}

### Creation Myth

**Type:** ${cultMyth.creationMyth.type}

${cultMyth.creationMyth.narrative}

**Primordial Elements:** ${cultMyth.creationMyth.primordialElements.join(', ')}
**Human Origin:** ${cultMyth.creationMyth.humanOrigin}

**First Beings:**
${cultMyth.creationMyth.firstBeings.map(b => `- **${b.name}**: ${b.nature} - ${b.fate}`).join('\n')}

### Heroes

${cultMyth.heroes.slice(0, 3).map(hero => `
#### ${hero.name}, ${hero.epithet}

**Origin:** ${hero.origin}
**Fate:** ${hero.fate}
**Legacy:** ${hero.legacy}

**Heroic Deeds:**
${hero.deeds.map(d => `- ${d}`).join('\n')}

${hero.companions > 0 ? `**Companions:** ${hero.companions}` : ''}
**Historical Basis:** ${hero.historicalBasis}
`).join('\n')}

${cultMyth.heroes.length > 3 ? `\n*... and ${cultMyth.heroes.length - 3} more heroes*\n` : ''}

### Monsters

${cultMyth.monsters.slice(0, 3).map(monster => `
#### ${monster.name}

**Form:** ${monster.form}
**Origin:** ${monster.origin}
**Status:** ${monster.status}
**Symbolism:** ${monster.symbolism}

**Powers:** ${monster.powers.join(', ')}
**Weakness:** ${monster.weakness}
`).join('\n')}

${cultMyth.monsters.length > 3 ? `\n*... and ${cultMyth.monsters.length - 3} more monsters*\n` : ''}

### Sacred Artifacts

${cultMyth.artifacts.slice(0, 3).map(artifact => `
#### ${artifact.name}

**Type:** ${artifact.type}
**Creator:** ${artifact.creator}
**Location:** ${artifact.location}

**Powers:** ${artifact.powers.join(', ')}
${artifact.curse ? `**Curse:** ${artifact.curse}` : ''}
${artifact.prophecy ? `**Prophecy:** ${artifact.prophecy}` : ''}
`).join('\n')}

${cultMyth.artifacts.length > 3 ? `\n*... and ${cultMyth.artifacts.length - 3} more artifacts*\n` : ''}

### Prophecies

${cultMyth.prophecies.map(prophecy => `
#### ${prophecy.name}

**Origin:** ${prophecy.origin}
**Interpretation:** ${prophecy.interpretation}
**Fulfillment:** ${prophecy.fulfillment}
**Significance:** ${prophecy.significance}

**Prediction:** ${prophecy.prediction}
`).join('\n')}

### Sacred Places

${cultMyth.sacredPlaces.map(place => `
- **${place.name}**: ${place.type} in ${place.location}
  - Significance: ${place.significance}
  - Access: ${place.access}
  - Phenomena: ${place.phenomena.join(', ')}
`).join('\n')}

`).join('\n')}
`;

  fs.writeFileSync(path.join(docsDir, 'mythology.md'), md);
}
